### ISSUE TITLE
Pokemon added by addons tend to not work with this resource pack

### ISSUE THREAD

**Issue by Mickeon** [Emery319/E19-CobblemonMinimapIcons#1]
Hello there. I hope you will read this issue report, despite the repository being completely empty.

Let me preface this by saying that the way the icons look in this Resource Pack is our personal favourite, on behalf of me, my friend, and people using the modpack we personally set up.

There are some Cobblemon addons out there that do not conform by the naming standard of the Cobblemon mod. For example, as of writing this, Blipbug is not "officially" present. An addon implements it as `blipbug`, but because the name is not `0824_blipbug`, the assumption of the resource pack is wrong and it does not work with these additional Pokemon.

Therefore, I suggest to at least have duplicate entries for the Pokemon, without the Dex number prefix, like https://modrinth.com/resourcepack/kiece-minimap-icons-cobblemon does.

**Comment by Emery319** [comment]
Thank you for using my resource pack, I understand that you want to add a Pokémon, I tried to add an entity with the dex number removed in the “definition” as you said, but after loading the resource pack an error occurs, simply duplicate entries doesn't solve the problem, Instead, it makes the texture pack unusable. 

I used Kiece's resource pack, and it also fails to display Pokémon icons for some addons that don't have a dex number prefix (like MissingMons).

Since different addons have different naming formats and special forms, they must be specifically adjusted to display correctly. If you have some favorite addons that you can't part with, please let me know the names. I'll try to make a special version adapted to these addons when I have time.

**Comment by Mickeon** [comment]
> Thank you for using my resource pack, I understand that you want to add some Pokémon, I tried to add entities with the dex number removed as you said, but after loading the resource pack an error occurs. Simply duplicate entries doesn't solve the problem, Instead, it makes the resource pack unusable.

I modified the resource pack based on my own suggestion:
[E19 Cobblemon Minimap Icons (edit).zip](https://github.com/Emery319/E19-CobblemonMinimapIcons/files/15264213/E19.Cobblemon.Minimap.Icons.edit.zip)
It _seems_ to work fine for our purposes now, but there may be some Pokemon which will need to be tweaked on a case-by-case basis.

> If you have some favorite addons that you can't part with, please let me know the names. 

A majority of the addons used by us were provided by my friend from the Cobblemon Discord server and there's no real direct link to them. Thank for reading, though, I appreciate it a lot.

**Comment by Emery319** [comment]
I know what the problem is, I'm using the 1.5 snapshot version of cobblemon and the same error occurs when I try to load your modified resource pack, but after rolling back the version to 1.4.1 everything works fine. There should be some changes in 1.5 that are causing the problem, I'll look for what's causing it.

**Comment by Emery319** [comment]
If you have upgraded Cobblemon to version 1.5, please ensure you are using version 1.1.2 and replace the original file (_assets/xaerominimap/entity/icon/definition/cobblemon/pokemon.json_) with this [pokemon.json](https://github.com/Emery319/E19-CobblemonMinimapIcons/files/15286671/pokemon.json).  

This should save you some time! :)

**Comment by Emery319** [comment]
Your proposal will be used after version 1.2.0 and later to get compatibility with more addons, thanks again for the solution!
